### ISSUE TITLE
Acquisition not rendering for Bpod files 

### ISSUE THREAD

**Issue by ywang-26** [ben-dichter-consulting/jaeger-lab-to-nwb#22]
Hi Ben and Luiz,

I noticed some issues after loading the NWB files for Bpod experiment. 

The files were converted successfully. However, under the acquisition -> BehavioralEvents -> Port_1_in (for example), it shows as "rendering". I assumed that a trace would show here to help visualize the image. Please see the the photo attached. 

Do you know what could be causing the issue? Thanks. 

<img width="1050" alt="Bpod_NWB_issue" src="https://user-images.githubusercontent.com/43519726/98564059-e72ff880-2279-11eb-9f08-105b4e490dbb.png">

**Comment by bendichter** [comment]
Thanks for the bug report, @meowater!

@luiztauffer, can you take a look at this?

**Comment by luiztauffer** [comment]
This was being saved as TimeSeries with timestamps only, without data. But now I'm refactoring the converter to use https://github.com/rly/ndx-events instead and this should solve the problem
